<!--
  Co se dá prototypovat: the layers diagram, drawn as code and zoomed out one
  layer per click. Generated by diagrams/vrstvy-prototypu.mjs together with
  public/vrstvy-prototypu.svg (the static version the IO chapter uses), so
  both share one geometry - edit the generator, not this file.

  Props:
    step: number   the slide's $clicks (frontmatter clicks: 4). 0 shows
                   only the innermost layer, 1-4 add one layer each and
                   pull the camera back; at 4 the caption comes in.
-->
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{ step?: number }>(), { step: 4 })

const cameras = [
  'translate(-246.2px, -265.8px) scale(1.4396)',
  'translate(-166.3px, -179.6px) scale(1.2970)',
  'translate(-100.9px, -109.0px) scale(1.1802)',
  'translate(-46.3px, -50.0px) scale(1.0826)',
  'translate(0.0px, 0.0px) scale(1.0000)'
]
const camera = computed(() => cameras[Math.max(0, Math.min(props.step, 4))])
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 540" class="vrstvy" role="img" aria-labelledby="title desc">
  <title id="title">Co se dá prototypovat: vrstvy, které do sebe zapadají</title>
  <desc id="desc">Pět vnořených vrstev od nejmenší po největší: obsah a texty (úřední dopis) uvnitř obrazovek a dílčích průchodů (dokončení objednávky), ty uvnitř zákaznické cesty (od objednávky po vrácení zboží), cesta ve fyzických prostorech a navigaci (zákaznické centrum úřadu) a to celé v produktové vizi (Knowledge Navigator, Apple 1987).</desc>
  
  <rect x="1" y="1" width="1118" height="538" rx="22" fill="#f6f8fb" stroke="#e2e8f0" stroke-width="1.5"/>
  <!-- the nesting, outermost first so each inner layer draws on top -->
  <g class="nest" :style="{ transform: camera }">
    <g class="layer" :class="{ on: step >= 4 }"><rect x="36" y="36" width="1048" height="430" rx="14" fill="rgb(255 255 255)" stroke="#c3d3e4" stroke-width="1.5"/><text class="muni" y="77.5" style="font-size: 18px" fill="#0000dc"><tspan x="58.0">PRODUKTOVÁ</tspan><tspan x="191.2">VIZE</tspan></text><text class="sans" x="902" y="77.5" style="font-size: 18px" text-anchor="end" fill="#1b1f24">Knowledge Navigator (Apple, 1987)</text></g>
    <g class="layer" :class="{ on: step >= 3 }"><rect x="76" y="106" width="968" height="344" rx="14" fill="rgb(246 252 255)" stroke="#c3d3e4" stroke-width="1.5"/><text class="muni" y="147.5" style="font-size: 18px" fill="#0000dc"><tspan x="98.0">FYZICKÉ</tspan><tspan x="193.4">PROSTORY</tspan><tspan x="301.4">A</tspan><tspan x="321.2">NAVIGACE</tspan></text><text class="sans" x="902" y="147.5" style="font-size: 18px" text-anchor="end" fill="#1b1f24">zákaznické centrum úřadu</text></g>
    <g class="layer" :class="{ on: step >= 2 }"><rect x="116" y="176" width="888" height="258" rx="14" fill="rgb(237 250 255)" stroke="#c3d3e4" stroke-width="1.5"/><text class="muni" y="217.5" style="font-size: 18px" fill="#0000dc"><tspan x="138.0">ZÁKAZNICKÁ</tspan><tspan x="271.2">CESTA</tspan></text><text class="sans" x="902" y="217.5" style="font-size: 18px" text-anchor="end" fill="#1b1f24">od objednávky po vrácení zboží</text></g>
    <g class="layer" :class="{ on: step >= 1 }"><rect x="156" y="246" width="808" height="172" rx="14" fill="rgb(228 247 255)" stroke="#c3d3e4" stroke-width="1.5"/><text class="muni" y="287.5" style="font-size: 18px" fill="#0000dc"><tspan x="178.0">OBRAZOVKY</tspan><tspan x="298.6">A</tspan><tspan x="318.4">DÍLČÍ</tspan><tspan x="388.6">PRŮCHODY</tspan></text><text class="sans" x="902" y="287.5" style="font-size: 18px" text-anchor="end" fill="#1b1f24">dokončení objednávky</text></g>
    <g class="layer" :class="{ on: step >= 0 }"><rect x="196" y="316" width="728" height="86" rx="14" fill="rgb(219 244 255)" stroke="#c3d3e4" stroke-width="1.5"/><text class="muni" y="365.5" style="font-size: 18px" fill="#0000dc"><tspan x="218.0">OBSAH</tspan><tspan x="288.2">A</tspan><tspan x="308.0">TEXTY</tspan></text><text class="sans" x="902" y="365.5" style="font-size: 18px" text-anchor="end" fill="#1b1f24">úřední dopis</text></g>
  </g>
  <g class="layer" :class="{ on: step >= 4 }"><text class="sans" x="36" y="504" style="font-size: 17px" fill="#595959">Každá vrstva je součástí té větší</text></g>
</svg>
</template>

<style scoped>
.vrstvy { width: 100%; height: auto; display: block; }
.muni { font-family: 'Muni', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 700; }
.sans { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }
.nest { transition: transform 0.8s cubic-bezier(0.22, 1, 0.36, 1); }
.layer { opacity: 0; transition: opacity 0.5s ease 0.15s; }
.layer.on { opacity: 1; }
</style>
